{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vyking-apps.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "vyking-apps.backend.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vyking-apps.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "vyking-apps.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
