{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vyking-apps.backend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vyking-apps.labels" . | nindent 4 }}
    {{- include "vyking-apps.backend.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "vyking-apps.protectionAnnotations" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vyking-apps.frontend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vyking-apps.labels" . | nindent 4 }}
    {{- include "vyking-apps.frontend.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "vyking-apps.protectionAnnotations" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
